// Code generated by tars2go 1.2.4, DO NOT EDIT.
// This file was generated from cms.tars
// Package cms comment
package cms

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"

	"github.com/TarsCloud/TarsGo/tars"
	"github.com/TarsCloud/TarsGo/tars/model"
	"github.com/TarsCloud/TarsGo/tars/protocol/codec"
	"github.com/TarsCloud/TarsGo/tars/protocol/res/basef"
	"github.com/TarsCloud/TarsGo/tars/protocol/res/requestf"
	"github.com/TarsCloud/TarsGo/tars/protocol/tup"
	"github.com/TarsCloud/TarsGo/tars/util/current"
	"github.com/TarsCloud/TarsGo/tars/util/endpoint"
	"github.com/TarsCloud/TarsGo/tars/util/tools"
	tarstrace "github.com/TarsCloud/TarsGo/tars/util/trace"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = fmt.Errorf
	_ = codec.FromInt8
	_ = bytes.ErrTooLarge
)

type AuthObjServant interface {
	Login(tenantId int32, username string, password string) (ret string, err error)
	Register(tenantId int32, username string, password string, email string) (ret string, err error)
	GetUserInfo(tenantId int32, token string) (ret string, err error)
	RefreshToken(tenantId int32, token string) (ret string, err error)
	Logout(tenantId int32, token string) (ret string, err error)
}

type AuthObjServantWithContext interface {
	Login(tarsCtx context.Context, tenantId int32, username string, password string) (ret string, err error)
	Register(tarsCtx context.Context, tenantId int32, username string, password string, email string) (ret string, err error)
	GetUserInfo(tarsCtx context.Context, tenantId int32, token string) (ret string, err error)
	RefreshToken(tarsCtx context.Context, tenantId int32, token string) (ret string, err error)
	Logout(tarsCtx context.Context, tenantId int32, token string) (ret string, err error)
}

// AuthObj struct
type AuthObj struct {
	servant model.Servant
}

// NewAuthObj creates a new AuthObj servant.
func NewAuthObj() *AuthObj {
	return new(AuthObj)
}

// NewAuthObjClient creates a new AuthObj client proxy for the given servant.
func NewAuthObjClient(servant string, comm *tars.Communicator, option ...tars.EndpointManagerOption) *AuthObj {
	client := new(AuthObj)
	comm.StringToProxy(servant, client, option...)
	return client
}

// SetServant sets servant for the service.
func (obj *AuthObj) SetServant(servant model.Servant) {
	obj.servant = servant
}

// TarsSetTimeout sets the timeout for the servant which is in ms.
func (obj *AuthObj) TarsSetTimeout(timeout int) {
	obj.servant.TarsSetTimeout(timeout)
}

// TarsSetProtocol sets the protocol for the servant.
func (obj *AuthObj) TarsSetProtocol(p model.Protocol) {
	obj.servant.TarsSetProtocol(p)
}

// Endpoints returns all active endpoint.Endpoint
func (obj *AuthObj) Endpoints() []*endpoint.Endpoint {
	return obj.servant.Endpoints()
}

// AddServant adds servant  for the service.
func (obj *AuthObj) AddServant(imp AuthObjServant, servant string) {
	tars.AddServant(obj, imp, servant)
}

// AddServantWithContext adds servant  for the service with context.
func (obj *AuthObj) AddServantWithContext(imp AuthObjServantWithContext, servant string) {
	tars.AddServantWithContext(obj, imp, servant)
}

// Login is the proxy function for the method defined in the tars file, with the context
func (obj *AuthObj) Login(tenantId int32, username string, password string, opts ...map[string]string) (string, error) {
	return obj.LoginWithContext(context.Background(), tenantId, username, password, opts...)
}

// LoginWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *AuthObj) LoginWithContext(tarsCtx context.Context, tenantId int32, username string, password string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(username, 2)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(password, 3)
	if err != nil {
		return ret, err
	}

	trace, ok := current.GetTarsTrace(tarsCtx)
	if ok && trace.Call() {
		var traceParam string
		trace.NewSpan()
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCS, uint(buf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value["tenantId"] = tenantId
			value["username"] = username
			value["password"] = password
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCS), tarstrace.AnnotationCS, tars.GetClientConfig().ModuleName, obj.servant.Name(), "login", 0, traceParam, "")
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 0, "login", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}
	readBuf := codec.NewReader(tools.Int8ToByte(tarsResp.SBuffer))
	err = readBuf.ReadString(&ret, 0, true)
	if err != nil {
		return ret, err
	}

	if ok && trace.Call() {
		var traceParam string
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCR, uint(readBuf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value[""] = ret
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCR), tarstrace.AnnotationCR, tars.GetClientConfig().ModuleName, obj.servant.Name(), "login", tarsResp.IRet, traceParam, "")
	}

	if len(opts) == 1 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
	} else if len(opts) == 2 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
		for k := range statusMap {
			delete(statusMap, k)
		}
		for k, v := range tarsResp.Status {
			statusMap[k] = v
		}
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// LoginOneWayWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *AuthObj) LoginOneWayWithContext(tarsCtx context.Context, tenantId int32, username string, password string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(username, 2)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(password, 3)
	if err != nil {
		return ret, err
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 1, "login", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// Register is the proxy function for the method defined in the tars file, with the context
func (obj *AuthObj) Register(tenantId int32, username string, password string, email string, opts ...map[string]string) (string, error) {
	return obj.RegisterWithContext(context.Background(), tenantId, username, password, email, opts...)
}

// RegisterWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *AuthObj) RegisterWithContext(tarsCtx context.Context, tenantId int32, username string, password string, email string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(username, 2)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(password, 3)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(email, 4)
	if err != nil {
		return ret, err
	}

	trace, ok := current.GetTarsTrace(tarsCtx)
	if ok && trace.Call() {
		var traceParam string
		trace.NewSpan()
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCS, uint(buf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value["tenantId"] = tenantId
			value["username"] = username
			value["password"] = password
			value["email"] = email
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCS), tarstrace.AnnotationCS, tars.GetClientConfig().ModuleName, obj.servant.Name(), "register", 0, traceParam, "")
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 0, "register", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}
	readBuf := codec.NewReader(tools.Int8ToByte(tarsResp.SBuffer))
	err = readBuf.ReadString(&ret, 0, true)
	if err != nil {
		return ret, err
	}

	if ok && trace.Call() {
		var traceParam string
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCR, uint(readBuf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value[""] = ret
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCR), tarstrace.AnnotationCR, tars.GetClientConfig().ModuleName, obj.servant.Name(), "register", tarsResp.IRet, traceParam, "")
	}

	if len(opts) == 1 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
	} else if len(opts) == 2 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
		for k := range statusMap {
			delete(statusMap, k)
		}
		for k, v := range tarsResp.Status {
			statusMap[k] = v
		}
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// RegisterOneWayWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *AuthObj) RegisterOneWayWithContext(tarsCtx context.Context, tenantId int32, username string, password string, email string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(username, 2)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(password, 3)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(email, 4)
	if err != nil {
		return ret, err
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 1, "register", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// GetUserInfo is the proxy function for the method defined in the tars file, with the context
func (obj *AuthObj) GetUserInfo(tenantId int32, token string, opts ...map[string]string) (string, error) {
	return obj.GetUserInfoWithContext(context.Background(), tenantId, token, opts...)
}

// GetUserInfoWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *AuthObj) GetUserInfoWithContext(tarsCtx context.Context, tenantId int32, token string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(token, 2)
	if err != nil {
		return ret, err
	}

	trace, ok := current.GetTarsTrace(tarsCtx)
	if ok && trace.Call() {
		var traceParam string
		trace.NewSpan()
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCS, uint(buf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value["tenantId"] = tenantId
			value["token"] = token
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCS), tarstrace.AnnotationCS, tars.GetClientConfig().ModuleName, obj.servant.Name(), "getUserInfo", 0, traceParam, "")
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 0, "getUserInfo", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}
	readBuf := codec.NewReader(tools.Int8ToByte(tarsResp.SBuffer))
	err = readBuf.ReadString(&ret, 0, true)
	if err != nil {
		return ret, err
	}

	if ok && trace.Call() {
		var traceParam string
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCR, uint(readBuf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value[""] = ret
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCR), tarstrace.AnnotationCR, tars.GetClientConfig().ModuleName, obj.servant.Name(), "getUserInfo", tarsResp.IRet, traceParam, "")
	}

	if len(opts) == 1 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
	} else if len(opts) == 2 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
		for k := range statusMap {
			delete(statusMap, k)
		}
		for k, v := range tarsResp.Status {
			statusMap[k] = v
		}
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// GetUserInfoOneWayWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *AuthObj) GetUserInfoOneWayWithContext(tarsCtx context.Context, tenantId int32, token string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(token, 2)
	if err != nil {
		return ret, err
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 1, "getUserInfo", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// RefreshToken is the proxy function for the method defined in the tars file, with the context
func (obj *AuthObj) RefreshToken(tenantId int32, token string, opts ...map[string]string) (string, error) {
	return obj.RefreshTokenWithContext(context.Background(), tenantId, token, opts...)
}

// RefreshTokenWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *AuthObj) RefreshTokenWithContext(tarsCtx context.Context, tenantId int32, token string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(token, 2)
	if err != nil {
		return ret, err
	}

	trace, ok := current.GetTarsTrace(tarsCtx)
	if ok && trace.Call() {
		var traceParam string
		trace.NewSpan()
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCS, uint(buf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value["tenantId"] = tenantId
			value["token"] = token
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCS), tarstrace.AnnotationCS, tars.GetClientConfig().ModuleName, obj.servant.Name(), "refreshToken", 0, traceParam, "")
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 0, "refreshToken", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}
	readBuf := codec.NewReader(tools.Int8ToByte(tarsResp.SBuffer))
	err = readBuf.ReadString(&ret, 0, true)
	if err != nil {
		return ret, err
	}

	if ok && trace.Call() {
		var traceParam string
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCR, uint(readBuf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value[""] = ret
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCR), tarstrace.AnnotationCR, tars.GetClientConfig().ModuleName, obj.servant.Name(), "refreshToken", tarsResp.IRet, traceParam, "")
	}

	if len(opts) == 1 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
	} else if len(opts) == 2 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
		for k := range statusMap {
			delete(statusMap, k)
		}
		for k, v := range tarsResp.Status {
			statusMap[k] = v
		}
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// RefreshTokenOneWayWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *AuthObj) RefreshTokenOneWayWithContext(tarsCtx context.Context, tenantId int32, token string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(token, 2)
	if err != nil {
		return ret, err
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 1, "refreshToken", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// Logout is the proxy function for the method defined in the tars file, with the context
func (obj *AuthObj) Logout(tenantId int32, token string, opts ...map[string]string) (string, error) {
	return obj.LogoutWithContext(context.Background(), tenantId, token, opts...)
}

// LogoutWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *AuthObj) LogoutWithContext(tarsCtx context.Context, tenantId int32, token string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(token, 2)
	if err != nil {
		return ret, err
	}

	trace, ok := current.GetTarsTrace(tarsCtx)
	if ok && trace.Call() {
		var traceParam string
		trace.NewSpan()
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCS, uint(buf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value["tenantId"] = tenantId
			value["token"] = token
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCS), tarstrace.AnnotationCS, tars.GetClientConfig().ModuleName, obj.servant.Name(), "logout", 0, traceParam, "")
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 0, "logout", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}
	readBuf := codec.NewReader(tools.Int8ToByte(tarsResp.SBuffer))
	err = readBuf.ReadString(&ret, 0, true)
	if err != nil {
		return ret, err
	}

	if ok && trace.Call() {
		var traceParam string
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCR, uint(readBuf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value[""] = ret
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCR), tarstrace.AnnotationCR, tars.GetClientConfig().ModuleName, obj.servant.Name(), "logout", tarsResp.IRet, traceParam, "")
	}

	if len(opts) == 1 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
	} else if len(opts) == 2 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
		for k := range statusMap {
			delete(statusMap, k)
		}
		for k, v := range tarsResp.Status {
			statusMap[k] = v
		}
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// LogoutOneWayWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *AuthObj) LogoutOneWayWithContext(tarsCtx context.Context, tenantId int32, token string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(token, 2)
	if err != nil {
		return ret, err
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 1, "logout", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// Dispatch is used to call the server side implement for the method defined in the tars file. withContext shows using context or not.
func (obj *AuthObj) Dispatch(tarsCtx context.Context, val interface{}, tarsReq *requestf.RequestPacket, tarsResp *requestf.ResponsePacket, withContext bool) (err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	readBuf := codec.NewReader(tools.Int8ToByte(tarsReq.SBuffer))
	buf := codec.NewBuffer()
	switch tarsReq.SFuncName {
	case "login":
		var tenantId int32
		var username string
		var password string
		if tarsReq.IVersion == basef.TARSVERSION {
			err = readBuf.ReadInt32(&tenantId, 1, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&username, 2, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&password, 3, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			reqTup := tup.NewUniAttribute()
			reqTup.Decode(readBuf)

			var tupBuffer []byte

			reqTup.GetBuffer("tenantId", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadInt32(&tenantId, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("username", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&username, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("password", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&password, 0, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			var jsonData map[string]interface{}
			decoder := json.NewDecoder(bytes.NewReader(readBuf.ToBytes()))
			decoder.UseNumber()
			err = decoder.Decode(&jsonData)
			if err != nil {
				return fmt.Errorf("decode reqpacket failed, error: %+v", err)
			}
			{
				jsonStr, _ := json.Marshal(jsonData["tenantId"])
				if err = json.Unmarshal(jsonStr, &tenantId); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["username"])
				if err = json.Unmarshal(jsonStr, &username); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["password"])
				if err = json.Unmarshal(jsonStr, &password); err != nil {
					return err
				}
			}
		} else {
			err = fmt.Errorf("decode reqpacket fail, error version: %d", tarsReq.IVersion)
			return err
		}

		trace, ok := current.GetTarsTrace(tarsCtx)
		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSR, uint(readBuf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value["tenantId"] = tenantId
				value["username"] = username
				value["password"] = password
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSR), tarstrace.AnnotationSR, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "login", 0, traceParam, "")
		}

		var funRet string
		if !withContext {
			imp := val.(AuthObjServant)
			funRet, err = imp.Login(tenantId, username, password)
		} else {
			imp := val.(AuthObjServantWithContext)
			funRet, err = imp.Login(tarsCtx, tenantId, username, password)
		}
		if err != nil {
			return err
		}

		if tarsReq.IVersion == basef.TARSVERSION {
			buf.Reset()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			rspTup := tup.NewUniAttribute()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}

			rspTup.PutBuffer("", buf.ToBytes())
			rspTup.PutBuffer("tars_ret", buf.ToBytes())

			buf.Reset()
			err = rspTup.Encode(buf)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			rspJson := map[string]interface{}{}
			rspJson["tars_ret"] = funRet

			var rspByte []byte
			if rspByte, err = json.Marshal(rspJson); err != nil {
				return err
			}

			buf.Reset()
			err = buf.WriteSliceUint8(rspByte)
			if err != nil {
				return err
			}
		}

		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSS, uint(buf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value[""] = funRet
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSS), tarstrace.AnnotationSS, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "login", 0, traceParam, "")
		}
	case "register":
		var tenantId int32
		var username string
		var password string
		var email string
		if tarsReq.IVersion == basef.TARSVERSION {
			err = readBuf.ReadInt32(&tenantId, 1, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&username, 2, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&password, 3, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&email, 4, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			reqTup := tup.NewUniAttribute()
			reqTup.Decode(readBuf)

			var tupBuffer []byte

			reqTup.GetBuffer("tenantId", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadInt32(&tenantId, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("username", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&username, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("password", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&password, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("email", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&email, 0, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			var jsonData map[string]interface{}
			decoder := json.NewDecoder(bytes.NewReader(readBuf.ToBytes()))
			decoder.UseNumber()
			err = decoder.Decode(&jsonData)
			if err != nil {
				return fmt.Errorf("decode reqpacket failed, error: %+v", err)
			}
			{
				jsonStr, _ := json.Marshal(jsonData["tenantId"])
				if err = json.Unmarshal(jsonStr, &tenantId); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["username"])
				if err = json.Unmarshal(jsonStr, &username); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["password"])
				if err = json.Unmarshal(jsonStr, &password); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["email"])
				if err = json.Unmarshal(jsonStr, &email); err != nil {
					return err
				}
			}
		} else {
			err = fmt.Errorf("decode reqpacket fail, error version: %d", tarsReq.IVersion)
			return err
		}

		trace, ok := current.GetTarsTrace(tarsCtx)
		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSR, uint(readBuf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value["tenantId"] = tenantId
				value["username"] = username
				value["password"] = password
				value["email"] = email
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSR), tarstrace.AnnotationSR, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "register", 0, traceParam, "")
		}

		var funRet string
		if !withContext {
			imp := val.(AuthObjServant)
			funRet, err = imp.Register(tenantId, username, password, email)
		} else {
			imp := val.(AuthObjServantWithContext)
			funRet, err = imp.Register(tarsCtx, tenantId, username, password, email)
		}
		if err != nil {
			return err
		}

		if tarsReq.IVersion == basef.TARSVERSION {
			buf.Reset()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			rspTup := tup.NewUniAttribute()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}

			rspTup.PutBuffer("", buf.ToBytes())
			rspTup.PutBuffer("tars_ret", buf.ToBytes())

			buf.Reset()
			err = rspTup.Encode(buf)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			rspJson := map[string]interface{}{}
			rspJson["tars_ret"] = funRet

			var rspByte []byte
			if rspByte, err = json.Marshal(rspJson); err != nil {
				return err
			}

			buf.Reset()
			err = buf.WriteSliceUint8(rspByte)
			if err != nil {
				return err
			}
		}

		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSS, uint(buf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value[""] = funRet
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSS), tarstrace.AnnotationSS, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "register", 0, traceParam, "")
		}
	case "getUserInfo":
		var tenantId int32
		var token string
		if tarsReq.IVersion == basef.TARSVERSION {
			err = readBuf.ReadInt32(&tenantId, 1, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&token, 2, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			reqTup := tup.NewUniAttribute()
			reqTup.Decode(readBuf)

			var tupBuffer []byte

			reqTup.GetBuffer("tenantId", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadInt32(&tenantId, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("token", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&token, 0, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			var jsonData map[string]interface{}
			decoder := json.NewDecoder(bytes.NewReader(readBuf.ToBytes()))
			decoder.UseNumber()
			err = decoder.Decode(&jsonData)
			if err != nil {
				return fmt.Errorf("decode reqpacket failed, error: %+v", err)
			}
			{
				jsonStr, _ := json.Marshal(jsonData["tenantId"])
				if err = json.Unmarshal(jsonStr, &tenantId); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["token"])
				if err = json.Unmarshal(jsonStr, &token); err != nil {
					return err
				}
			}
		} else {
			err = fmt.Errorf("decode reqpacket fail, error version: %d", tarsReq.IVersion)
			return err
		}

		trace, ok := current.GetTarsTrace(tarsCtx)
		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSR, uint(readBuf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value["tenantId"] = tenantId
				value["token"] = token
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSR), tarstrace.AnnotationSR, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "getUserInfo", 0, traceParam, "")
		}

		var funRet string
		if !withContext {
			imp := val.(AuthObjServant)
			funRet, err = imp.GetUserInfo(tenantId, token)
		} else {
			imp := val.(AuthObjServantWithContext)
			funRet, err = imp.GetUserInfo(tarsCtx, tenantId, token)
		}
		if err != nil {
			return err
		}

		if tarsReq.IVersion == basef.TARSVERSION {
			buf.Reset()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			rspTup := tup.NewUniAttribute()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}

			rspTup.PutBuffer("", buf.ToBytes())
			rspTup.PutBuffer("tars_ret", buf.ToBytes())

			buf.Reset()
			err = rspTup.Encode(buf)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			rspJson := map[string]interface{}{}
			rspJson["tars_ret"] = funRet

			var rspByte []byte
			if rspByte, err = json.Marshal(rspJson); err != nil {
				return err
			}

			buf.Reset()
			err = buf.WriteSliceUint8(rspByte)
			if err != nil {
				return err
			}
		}

		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSS, uint(buf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value[""] = funRet
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSS), tarstrace.AnnotationSS, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "getUserInfo", 0, traceParam, "")
		}
	case "refreshToken":
		var tenantId int32
		var token string
		if tarsReq.IVersion == basef.TARSVERSION {
			err = readBuf.ReadInt32(&tenantId, 1, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&token, 2, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			reqTup := tup.NewUniAttribute()
			reqTup.Decode(readBuf)

			var tupBuffer []byte

			reqTup.GetBuffer("tenantId", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadInt32(&tenantId, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("token", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&token, 0, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			var jsonData map[string]interface{}
			decoder := json.NewDecoder(bytes.NewReader(readBuf.ToBytes()))
			decoder.UseNumber()
			err = decoder.Decode(&jsonData)
			if err != nil {
				return fmt.Errorf("decode reqpacket failed, error: %+v", err)
			}
			{
				jsonStr, _ := json.Marshal(jsonData["tenantId"])
				if err = json.Unmarshal(jsonStr, &tenantId); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["token"])
				if err = json.Unmarshal(jsonStr, &token); err != nil {
					return err
				}
			}
		} else {
			err = fmt.Errorf("decode reqpacket fail, error version: %d", tarsReq.IVersion)
			return err
		}

		trace, ok := current.GetTarsTrace(tarsCtx)
		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSR, uint(readBuf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value["tenantId"] = tenantId
				value["token"] = token
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSR), tarstrace.AnnotationSR, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "refreshToken", 0, traceParam, "")
		}

		var funRet string
		if !withContext {
			imp := val.(AuthObjServant)
			funRet, err = imp.RefreshToken(tenantId, token)
		} else {
			imp := val.(AuthObjServantWithContext)
			funRet, err = imp.RefreshToken(tarsCtx, tenantId, token)
		}
		if err != nil {
			return err
		}

		if tarsReq.IVersion == basef.TARSVERSION {
			buf.Reset()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			rspTup := tup.NewUniAttribute()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}

			rspTup.PutBuffer("", buf.ToBytes())
			rspTup.PutBuffer("tars_ret", buf.ToBytes())

			buf.Reset()
			err = rspTup.Encode(buf)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			rspJson := map[string]interface{}{}
			rspJson["tars_ret"] = funRet

			var rspByte []byte
			if rspByte, err = json.Marshal(rspJson); err != nil {
				return err
			}

			buf.Reset()
			err = buf.WriteSliceUint8(rspByte)
			if err != nil {
				return err
			}
		}

		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSS, uint(buf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value[""] = funRet
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSS), tarstrace.AnnotationSS, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "refreshToken", 0, traceParam, "")
		}
	case "logout":
		var tenantId int32
		var token string
		if tarsReq.IVersion == basef.TARSVERSION {
			err = readBuf.ReadInt32(&tenantId, 1, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&token, 2, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			reqTup := tup.NewUniAttribute()
			reqTup.Decode(readBuf)

			var tupBuffer []byte

			reqTup.GetBuffer("tenantId", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadInt32(&tenantId, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("token", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&token, 0, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			var jsonData map[string]interface{}
			decoder := json.NewDecoder(bytes.NewReader(readBuf.ToBytes()))
			decoder.UseNumber()
			err = decoder.Decode(&jsonData)
			if err != nil {
				return fmt.Errorf("decode reqpacket failed, error: %+v", err)
			}
			{
				jsonStr, _ := json.Marshal(jsonData["tenantId"])
				if err = json.Unmarshal(jsonStr, &tenantId); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["token"])
				if err = json.Unmarshal(jsonStr, &token); err != nil {
					return err
				}
			}
		} else {
			err = fmt.Errorf("decode reqpacket fail, error version: %d", tarsReq.IVersion)
			return err
		}

		trace, ok := current.GetTarsTrace(tarsCtx)
		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSR, uint(readBuf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value["tenantId"] = tenantId
				value["token"] = token
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSR), tarstrace.AnnotationSR, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "logout", 0, traceParam, "")
		}

		var funRet string
		if !withContext {
			imp := val.(AuthObjServant)
			funRet, err = imp.Logout(tenantId, token)
		} else {
			imp := val.(AuthObjServantWithContext)
			funRet, err = imp.Logout(tarsCtx, tenantId, token)
		}
		if err != nil {
			return err
		}

		if tarsReq.IVersion == basef.TARSVERSION {
			buf.Reset()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			rspTup := tup.NewUniAttribute()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}

			rspTup.PutBuffer("", buf.ToBytes())
			rspTup.PutBuffer("tars_ret", buf.ToBytes())

			buf.Reset()
			err = rspTup.Encode(buf)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			rspJson := map[string]interface{}{}
			rspJson["tars_ret"] = funRet

			var rspByte []byte
			if rspByte, err = json.Marshal(rspJson); err != nil {
				return err
			}

			buf.Reset()
			err = buf.WriteSliceUint8(rspByte)
			if err != nil {
				return err
			}
		}

		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSS, uint(buf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value[""] = funRet
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSS), tarstrace.AnnotationSS, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "logout", 0, traceParam, "")
		}

	default:
		return fmt.Errorf("func mismatch")
	}
	var statusMap map[string]string
	if status, ok := current.GetResponseStatus(tarsCtx); ok && status != nil {
		statusMap = status
	}
	var contextMap map[string]string
	if ctx, ok := current.GetResponseContext(tarsCtx); ok && ctx != nil {
		contextMap = ctx
	}
	*tarsResp = requestf.ResponsePacket{
		IVersion:     tarsReq.IVersion,
		CPacketType:  0,
		IRequestId:   tarsReq.IRequestId,
		IMessageType: 0,
		IRet:         0,
		SBuffer:      tools.ByteToInt8(buf.ToBytes()),
		Status:       statusMap,
		SResultDesc:  "",
		Context:      contextMap,
	}

	_ = readBuf
	_ = buf
	_ = length
	_ = have
	_ = ty
	return nil
}
