// Code generated by tars2go 1.2.4, DO NOT EDIT.
// This file was generated from wx.tars
// Package wx comment
package wx

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"

	"github.com/TarsCloud/TarsGo/tars"
	"github.com/TarsCloud/TarsGo/tars/model"
	"github.com/TarsCloud/TarsGo/tars/protocol/codec"
	"github.com/TarsCloud/TarsGo/tars/protocol/res/basef"
	"github.com/TarsCloud/TarsGo/tars/protocol/res/requestf"
	"github.com/TarsCloud/TarsGo/tars/protocol/tup"
	"github.com/TarsCloud/TarsGo/tars/util/current"
	"github.com/TarsCloud/TarsGo/tars/util/endpoint"
	"github.com/TarsCloud/TarsGo/tars/util/tools"
	tarstrace "github.com/TarsCloud/TarsGo/tars/util/trace"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = fmt.Errorf
	_ = codec.FromInt8
	_ = bytes.ErrTooLarge
)

type MaObjServant interface {
	Code2Session(tenantId int32, appid string, jsCode string) (ret string, err error)
	GetAccessToken(tenantId int32, appid string) (ret string, err error)
	SendSubscribeMsg(tenantId int32, appid string, openid string, templateId string, dataJson string, page string) (ret string, err error)
	CheckSession(tenantId int32, openid string, sessionKey string) (ret string, err error)
}

type MaObjServantWithContext interface {
	Code2Session(tarsCtx context.Context, tenantId int32, appid string, jsCode string) (ret string, err error)
	GetAccessToken(tarsCtx context.Context, tenantId int32, appid string) (ret string, err error)
	SendSubscribeMsg(tarsCtx context.Context, tenantId int32, appid string, openid string, templateId string, dataJson string, page string) (ret string, err error)
	CheckSession(tarsCtx context.Context, tenantId int32, openid string, sessionKey string) (ret string, err error)
}

// MaObj struct
type MaObj struct {
	servant model.Servant
}

// NewMaObj creates a new MaObj servant.
func NewMaObj() *MaObj {
	return new(MaObj)
}

// NewMaObjClient creates a new MaObj client proxy for the given servant.
func NewMaObjClient(servant string, comm *tars.Communicator, option ...tars.EndpointManagerOption) *MaObj {
	client := new(MaObj)
	comm.StringToProxy(servant, client, option...)
	return client
}

// SetServant sets servant for the service.
func (obj *MaObj) SetServant(servant model.Servant) {
	obj.servant = servant
}

// TarsSetTimeout sets the timeout for the servant which is in ms.
func (obj *MaObj) TarsSetTimeout(timeout int) {
	obj.servant.TarsSetTimeout(timeout)
}

// TarsSetProtocol sets the protocol for the servant.
func (obj *MaObj) TarsSetProtocol(p model.Protocol) {
	obj.servant.TarsSetProtocol(p)
}

// Endpoints returns all active endpoint.Endpoint
func (obj *MaObj) Endpoints() []*endpoint.Endpoint {
	return obj.servant.Endpoints()
}

// AddServant adds servant  for the service.
func (obj *MaObj) AddServant(imp MaObjServant, servant string) {
	tars.AddServant(obj, imp, servant)
}

// AddServantWithContext adds servant  for the service with context.
func (obj *MaObj) AddServantWithContext(imp MaObjServantWithContext, servant string) {
	tars.AddServantWithContext(obj, imp, servant)
}

// Code2Session is the proxy function for the method defined in the tars file, with the context
func (obj *MaObj) Code2Session(tenantId int32, appid string, jsCode string, opts ...map[string]string) (string, error) {
	return obj.Code2SessionWithContext(context.Background(), tenantId, appid, jsCode, opts...)
}

// Code2SessionWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MaObj) Code2SessionWithContext(tarsCtx context.Context, tenantId int32, appid string, jsCode string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(appid, 2)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(jsCode, 3)
	if err != nil {
		return ret, err
	}

	trace, ok := current.GetTarsTrace(tarsCtx)
	if ok && trace.Call() {
		var traceParam string
		trace.NewSpan()
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCS, uint(buf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value["tenantId"] = tenantId
			value["appid"] = appid
			value["jsCode"] = jsCode
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCS), tarstrace.AnnotationCS, tars.GetClientConfig().ModuleName, obj.servant.Name(), "code2Session", 0, traceParam, "")
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 0, "code2Session", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}
	readBuf := codec.NewReader(tools.Int8ToByte(tarsResp.SBuffer))
	err = readBuf.ReadString(&ret, 0, true)
	if err != nil {
		return ret, err
	}

	if ok && trace.Call() {
		var traceParam string
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCR, uint(readBuf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value[""] = ret
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCR), tarstrace.AnnotationCR, tars.GetClientConfig().ModuleName, obj.servant.Name(), "code2Session", tarsResp.IRet, traceParam, "")
	}

	if len(opts) == 1 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
	} else if len(opts) == 2 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
		for k := range statusMap {
			delete(statusMap, k)
		}
		for k, v := range tarsResp.Status {
			statusMap[k] = v
		}
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// Code2SessionOneWayWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MaObj) Code2SessionOneWayWithContext(tarsCtx context.Context, tenantId int32, appid string, jsCode string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(appid, 2)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(jsCode, 3)
	if err != nil {
		return ret, err
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 1, "code2Session", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// GetAccessToken is the proxy function for the method defined in the tars file, with the context
func (obj *MaObj) GetAccessToken(tenantId int32, appid string, opts ...map[string]string) (string, error) {
	return obj.GetAccessTokenWithContext(context.Background(), tenantId, appid, opts...)
}

// GetAccessTokenWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MaObj) GetAccessTokenWithContext(tarsCtx context.Context, tenantId int32, appid string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(appid, 2)
	if err != nil {
		return ret, err
	}

	trace, ok := current.GetTarsTrace(tarsCtx)
	if ok && trace.Call() {
		var traceParam string
		trace.NewSpan()
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCS, uint(buf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value["tenantId"] = tenantId
			value["appid"] = appid
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCS), tarstrace.AnnotationCS, tars.GetClientConfig().ModuleName, obj.servant.Name(), "getAccessToken", 0, traceParam, "")
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 0, "getAccessToken", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}
	readBuf := codec.NewReader(tools.Int8ToByte(tarsResp.SBuffer))
	err = readBuf.ReadString(&ret, 0, true)
	if err != nil {
		return ret, err
	}

	if ok && trace.Call() {
		var traceParam string
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCR, uint(readBuf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value[""] = ret
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCR), tarstrace.AnnotationCR, tars.GetClientConfig().ModuleName, obj.servant.Name(), "getAccessToken", tarsResp.IRet, traceParam, "")
	}

	if len(opts) == 1 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
	} else if len(opts) == 2 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
		for k := range statusMap {
			delete(statusMap, k)
		}
		for k, v := range tarsResp.Status {
			statusMap[k] = v
		}
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// GetAccessTokenOneWayWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MaObj) GetAccessTokenOneWayWithContext(tarsCtx context.Context, tenantId int32, appid string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(appid, 2)
	if err != nil {
		return ret, err
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 1, "getAccessToken", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// SendSubscribeMsg is the proxy function for the method defined in the tars file, with the context
func (obj *MaObj) SendSubscribeMsg(tenantId int32, appid string, openid string, templateId string, dataJson string, page string, opts ...map[string]string) (string, error) {
	return obj.SendSubscribeMsgWithContext(context.Background(), tenantId, appid, openid, templateId, dataJson, page, opts...)
}

// SendSubscribeMsgWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MaObj) SendSubscribeMsgWithContext(tarsCtx context.Context, tenantId int32, appid string, openid string, templateId string, dataJson string, page string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(appid, 2)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(openid, 3)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(templateId, 4)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(dataJson, 5)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(page, 6)
	if err != nil {
		return ret, err
	}

	trace, ok := current.GetTarsTrace(tarsCtx)
	if ok && trace.Call() {
		var traceParam string
		trace.NewSpan()
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCS, uint(buf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value["tenantId"] = tenantId
			value["appid"] = appid
			value["openid"] = openid
			value["templateId"] = templateId
			value["dataJson"] = dataJson
			value["page"] = page
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCS), tarstrace.AnnotationCS, tars.GetClientConfig().ModuleName, obj.servant.Name(), "sendSubscribeMsg", 0, traceParam, "")
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 0, "sendSubscribeMsg", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}
	readBuf := codec.NewReader(tools.Int8ToByte(tarsResp.SBuffer))
	err = readBuf.ReadString(&ret, 0, true)
	if err != nil {
		return ret, err
	}

	if ok && trace.Call() {
		var traceParam string
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCR, uint(readBuf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value[""] = ret
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCR), tarstrace.AnnotationCR, tars.GetClientConfig().ModuleName, obj.servant.Name(), "sendSubscribeMsg", tarsResp.IRet, traceParam, "")
	}

	if len(opts) == 1 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
	} else if len(opts) == 2 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
		for k := range statusMap {
			delete(statusMap, k)
		}
		for k, v := range tarsResp.Status {
			statusMap[k] = v
		}
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// SendSubscribeMsgOneWayWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MaObj) SendSubscribeMsgOneWayWithContext(tarsCtx context.Context, tenantId int32, appid string, openid string, templateId string, dataJson string, page string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(appid, 2)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(openid, 3)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(templateId, 4)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(dataJson, 5)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(page, 6)
	if err != nil {
		return ret, err
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 1, "sendSubscribeMsg", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// CheckSession is the proxy function for the method defined in the tars file, with the context
func (obj *MaObj) CheckSession(tenantId int32, openid string, sessionKey string, opts ...map[string]string) (string, error) {
	return obj.CheckSessionWithContext(context.Background(), tenantId, openid, sessionKey, opts...)
}

// CheckSessionWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MaObj) CheckSessionWithContext(tarsCtx context.Context, tenantId int32, openid string, sessionKey string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(openid, 2)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(sessionKey, 3)
	if err != nil {
		return ret, err
	}

	trace, ok := current.GetTarsTrace(tarsCtx)
	if ok && trace.Call() {
		var traceParam string
		trace.NewSpan()
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCS, uint(buf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value["tenantId"] = tenantId
			value["openid"] = openid
			value["sessionKey"] = sessionKey
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCS), tarstrace.AnnotationCS, tars.GetClientConfig().ModuleName, obj.servant.Name(), "checkSession", 0, traceParam, "")
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 0, "checkSession", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}
	readBuf := codec.NewReader(tools.Int8ToByte(tarsResp.SBuffer))
	err = readBuf.ReadString(&ret, 0, true)
	if err != nil {
		return ret, err
	}

	if ok && trace.Call() {
		var traceParam string
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCR, uint(readBuf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value[""] = ret
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCR), tarstrace.AnnotationCR, tars.GetClientConfig().ModuleName, obj.servant.Name(), "checkSession", tarsResp.IRet, traceParam, "")
	}

	if len(opts) == 1 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
	} else if len(opts) == 2 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
		for k := range statusMap {
			delete(statusMap, k)
		}
		for k, v := range tarsResp.Status {
			statusMap[k] = v
		}
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// CheckSessionOneWayWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MaObj) CheckSessionOneWayWithContext(tarsCtx context.Context, tenantId int32, openid string, sessionKey string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(openid, 2)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(sessionKey, 3)
	if err != nil {
		return ret, err
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 1, "checkSession", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// Dispatch is used to call the server side implement for the method defined in the tars file. withContext shows using context or not.
func (obj *MaObj) Dispatch(tarsCtx context.Context, val interface{}, tarsReq *requestf.RequestPacket, tarsResp *requestf.ResponsePacket, withContext bool) (err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	readBuf := codec.NewReader(tools.Int8ToByte(tarsReq.SBuffer))
	buf := codec.NewBuffer()
	switch tarsReq.SFuncName {
	case "code2Session":
		var tenantId int32
		var appid string
		var jsCode string
		if tarsReq.IVersion == basef.TARSVERSION {
			err = readBuf.ReadInt32(&tenantId, 1, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&appid, 2, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&jsCode, 3, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			reqTup := tup.NewUniAttribute()
			reqTup.Decode(readBuf)

			var tupBuffer []byte

			reqTup.GetBuffer("tenantId", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadInt32(&tenantId, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("appid", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&appid, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("jsCode", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&jsCode, 0, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			var jsonData map[string]interface{}
			decoder := json.NewDecoder(bytes.NewReader(readBuf.ToBytes()))
			decoder.UseNumber()
			err = decoder.Decode(&jsonData)
			if err != nil {
				return fmt.Errorf("decode reqpacket failed, error: %+v", err)
			}
			{
				jsonStr, _ := json.Marshal(jsonData["tenantId"])
				if err = json.Unmarshal(jsonStr, &tenantId); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["appid"])
				if err = json.Unmarshal(jsonStr, &appid); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["jsCode"])
				if err = json.Unmarshal(jsonStr, &jsCode); err != nil {
					return err
				}
			}
		} else {
			err = fmt.Errorf("decode reqpacket fail, error version: %d", tarsReq.IVersion)
			return err
		}

		trace, ok := current.GetTarsTrace(tarsCtx)
		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSR, uint(readBuf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value["tenantId"] = tenantId
				value["appid"] = appid
				value["jsCode"] = jsCode
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSR), tarstrace.AnnotationSR, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "code2Session", 0, traceParam, "")
		}

		var funRet string
		if !withContext {
			imp := val.(MaObjServant)
			funRet, err = imp.Code2Session(tenantId, appid, jsCode)
		} else {
			imp := val.(MaObjServantWithContext)
			funRet, err = imp.Code2Session(tarsCtx, tenantId, appid, jsCode)
		}
		if err != nil {
			return err
		}

		if tarsReq.IVersion == basef.TARSVERSION {
			buf.Reset()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			rspTup := tup.NewUniAttribute()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}

			rspTup.PutBuffer("", buf.ToBytes())
			rspTup.PutBuffer("tars_ret", buf.ToBytes())

			buf.Reset()
			err = rspTup.Encode(buf)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			rspJson := map[string]interface{}{}
			rspJson["tars_ret"] = funRet

			var rspByte []byte
			if rspByte, err = json.Marshal(rspJson); err != nil {
				return err
			}

			buf.Reset()
			err = buf.WriteSliceUint8(rspByte)
			if err != nil {
				return err
			}
		}

		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSS, uint(buf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value[""] = funRet
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSS), tarstrace.AnnotationSS, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "code2Session", 0, traceParam, "")
		}
	case "getAccessToken":
		var tenantId int32
		var appid string
		if tarsReq.IVersion == basef.TARSVERSION {
			err = readBuf.ReadInt32(&tenantId, 1, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&appid, 2, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			reqTup := tup.NewUniAttribute()
			reqTup.Decode(readBuf)

			var tupBuffer []byte

			reqTup.GetBuffer("tenantId", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadInt32(&tenantId, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("appid", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&appid, 0, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			var jsonData map[string]interface{}
			decoder := json.NewDecoder(bytes.NewReader(readBuf.ToBytes()))
			decoder.UseNumber()
			err = decoder.Decode(&jsonData)
			if err != nil {
				return fmt.Errorf("decode reqpacket failed, error: %+v", err)
			}
			{
				jsonStr, _ := json.Marshal(jsonData["tenantId"])
				if err = json.Unmarshal(jsonStr, &tenantId); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["appid"])
				if err = json.Unmarshal(jsonStr, &appid); err != nil {
					return err
				}
			}
		} else {
			err = fmt.Errorf("decode reqpacket fail, error version: %d", tarsReq.IVersion)
			return err
		}

		trace, ok := current.GetTarsTrace(tarsCtx)
		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSR, uint(readBuf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value["tenantId"] = tenantId
				value["appid"] = appid
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSR), tarstrace.AnnotationSR, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "getAccessToken", 0, traceParam, "")
		}

		var funRet string
		if !withContext {
			imp := val.(MaObjServant)
			funRet, err = imp.GetAccessToken(tenantId, appid)
		} else {
			imp := val.(MaObjServantWithContext)
			funRet, err = imp.GetAccessToken(tarsCtx, tenantId, appid)
		}
		if err != nil {
			return err
		}

		if tarsReq.IVersion == basef.TARSVERSION {
			buf.Reset()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			rspTup := tup.NewUniAttribute()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}

			rspTup.PutBuffer("", buf.ToBytes())
			rspTup.PutBuffer("tars_ret", buf.ToBytes())

			buf.Reset()
			err = rspTup.Encode(buf)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			rspJson := map[string]interface{}{}
			rspJson["tars_ret"] = funRet

			var rspByte []byte
			if rspByte, err = json.Marshal(rspJson); err != nil {
				return err
			}

			buf.Reset()
			err = buf.WriteSliceUint8(rspByte)
			if err != nil {
				return err
			}
		}

		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSS, uint(buf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value[""] = funRet
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSS), tarstrace.AnnotationSS, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "getAccessToken", 0, traceParam, "")
		}
	case "sendSubscribeMsg":
		var tenantId int32
		var appid string
		var openid string
		var templateId string
		var dataJson string
		var page string
		if tarsReq.IVersion == basef.TARSVERSION {
			err = readBuf.ReadInt32(&tenantId, 1, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&appid, 2, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&openid, 3, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&templateId, 4, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&dataJson, 5, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&page, 6, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			reqTup := tup.NewUniAttribute()
			reqTup.Decode(readBuf)

			var tupBuffer []byte

			reqTup.GetBuffer("tenantId", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadInt32(&tenantId, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("appid", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&appid, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("openid", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&openid, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("templateId", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&templateId, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("dataJson", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&dataJson, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("page", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&page, 0, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			var jsonData map[string]interface{}
			decoder := json.NewDecoder(bytes.NewReader(readBuf.ToBytes()))
			decoder.UseNumber()
			err = decoder.Decode(&jsonData)
			if err != nil {
				return fmt.Errorf("decode reqpacket failed, error: %+v", err)
			}
			{
				jsonStr, _ := json.Marshal(jsonData["tenantId"])
				if err = json.Unmarshal(jsonStr, &tenantId); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["appid"])
				if err = json.Unmarshal(jsonStr, &appid); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["openid"])
				if err = json.Unmarshal(jsonStr, &openid); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["templateId"])
				if err = json.Unmarshal(jsonStr, &templateId); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["dataJson"])
				if err = json.Unmarshal(jsonStr, &dataJson); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["page"])
				if err = json.Unmarshal(jsonStr, &page); err != nil {
					return err
				}
			}
		} else {
			err = fmt.Errorf("decode reqpacket fail, error version: %d", tarsReq.IVersion)
			return err
		}

		trace, ok := current.GetTarsTrace(tarsCtx)
		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSR, uint(readBuf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value["tenantId"] = tenantId
				value["appid"] = appid
				value["openid"] = openid
				value["templateId"] = templateId
				value["dataJson"] = dataJson
				value["page"] = page
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSR), tarstrace.AnnotationSR, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "sendSubscribeMsg", 0, traceParam, "")
		}

		var funRet string
		if !withContext {
			imp := val.(MaObjServant)
			funRet, err = imp.SendSubscribeMsg(tenantId, appid, openid, templateId, dataJson, page)
		} else {
			imp := val.(MaObjServantWithContext)
			funRet, err = imp.SendSubscribeMsg(tarsCtx, tenantId, appid, openid, templateId, dataJson, page)
		}
		if err != nil {
			return err
		}

		if tarsReq.IVersion == basef.TARSVERSION {
			buf.Reset()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			rspTup := tup.NewUniAttribute()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}

			rspTup.PutBuffer("", buf.ToBytes())
			rspTup.PutBuffer("tars_ret", buf.ToBytes())

			buf.Reset()
			err = rspTup.Encode(buf)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			rspJson := map[string]interface{}{}
			rspJson["tars_ret"] = funRet

			var rspByte []byte
			if rspByte, err = json.Marshal(rspJson); err != nil {
				return err
			}

			buf.Reset()
			err = buf.WriteSliceUint8(rspByte)
			if err != nil {
				return err
			}
		}

		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSS, uint(buf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value[""] = funRet
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSS), tarstrace.AnnotationSS, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "sendSubscribeMsg", 0, traceParam, "")
		}
	case "checkSession":
		var tenantId int32
		var openid string
		var sessionKey string
		if tarsReq.IVersion == basef.TARSVERSION {
			err = readBuf.ReadInt32(&tenantId, 1, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&openid, 2, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&sessionKey, 3, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			reqTup := tup.NewUniAttribute()
			reqTup.Decode(readBuf)

			var tupBuffer []byte

			reqTup.GetBuffer("tenantId", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadInt32(&tenantId, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("openid", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&openid, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("sessionKey", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&sessionKey, 0, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			var jsonData map[string]interface{}
			decoder := json.NewDecoder(bytes.NewReader(readBuf.ToBytes()))
			decoder.UseNumber()
			err = decoder.Decode(&jsonData)
			if err != nil {
				return fmt.Errorf("decode reqpacket failed, error: %+v", err)
			}
			{
				jsonStr, _ := json.Marshal(jsonData["tenantId"])
				if err = json.Unmarshal(jsonStr, &tenantId); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["openid"])
				if err = json.Unmarshal(jsonStr, &openid); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["sessionKey"])
				if err = json.Unmarshal(jsonStr, &sessionKey); err != nil {
					return err
				}
			}
		} else {
			err = fmt.Errorf("decode reqpacket fail, error version: %d", tarsReq.IVersion)
			return err
		}

		trace, ok := current.GetTarsTrace(tarsCtx)
		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSR, uint(readBuf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value["tenantId"] = tenantId
				value["openid"] = openid
				value["sessionKey"] = sessionKey
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSR), tarstrace.AnnotationSR, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "checkSession", 0, traceParam, "")
		}

		var funRet string
		if !withContext {
			imp := val.(MaObjServant)
			funRet, err = imp.CheckSession(tenantId, openid, sessionKey)
		} else {
			imp := val.(MaObjServantWithContext)
			funRet, err = imp.CheckSession(tarsCtx, tenantId, openid, sessionKey)
		}
		if err != nil {
			return err
		}

		if tarsReq.IVersion == basef.TARSVERSION {
			buf.Reset()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			rspTup := tup.NewUniAttribute()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}

			rspTup.PutBuffer("", buf.ToBytes())
			rspTup.PutBuffer("tars_ret", buf.ToBytes())

			buf.Reset()
			err = rspTup.Encode(buf)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			rspJson := map[string]interface{}{}
			rspJson["tars_ret"] = funRet

			var rspByte []byte
			if rspByte, err = json.Marshal(rspJson); err != nil {
				return err
			}

			buf.Reset()
			err = buf.WriteSliceUint8(rspByte)
			if err != nil {
				return err
			}
		}

		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSS, uint(buf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value[""] = funRet
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSS), tarstrace.AnnotationSS, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "checkSession", 0, traceParam, "")
		}

	default:
		return fmt.Errorf("func mismatch")
	}
	var statusMap map[string]string
	if status, ok := current.GetResponseStatus(tarsCtx); ok && status != nil {
		statusMap = status
	}
	var contextMap map[string]string
	if ctx, ok := current.GetResponseContext(tarsCtx); ok && ctx != nil {
		contextMap = ctx
	}
	*tarsResp = requestf.ResponsePacket{
		IVersion:     tarsReq.IVersion,
		CPacketType:  0,
		IRequestId:   tarsReq.IRequestId,
		IMessageType: 0,
		IRet:         0,
		SBuffer:      tools.ByteToInt8(buf.ToBytes()),
		Status:       statusMap,
		SResultDesc:  "",
		Context:      contextMap,
	}

	_ = readBuf
	_ = buf
	_ = length
	_ = have
	_ = ty
	return nil
}
