// Code generated by tars2go 1.2.4, DO NOT EDIT.
// This file was generated from wx.tars
// Package wx comment
package wx

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"

	"github.com/TarsCloud/TarsGo/tars"
	"github.com/TarsCloud/TarsGo/tars/model"
	"github.com/TarsCloud/TarsGo/tars/protocol/codec"
	"github.com/TarsCloud/TarsGo/tars/protocol/res/basef"
	"github.com/TarsCloud/TarsGo/tars/protocol/res/requestf"
	"github.com/TarsCloud/TarsGo/tars/protocol/tup"
	"github.com/TarsCloud/TarsGo/tars/util/current"
	"github.com/TarsCloud/TarsGo/tars/util/endpoint"
	"github.com/TarsCloud/TarsGo/tars/util/tools"
	tarstrace "github.com/TarsCloud/TarsGo/tars/util/trace"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = fmt.Errorf
	_ = codec.FromInt8
	_ = bytes.ErrTooLarge
)

type MpObjServant interface {
	GetAccessToken(tenantId int32, appid string) (ret string, err error)
	RefreshAccessToken(tenantId int32, appid string) (ret string, err error)
	GetUserInfo(tenantId int32, appid string, openid string) (ret string, err error)
	SendTemplateMsg(tenantId int32, appid string, openid string, templateId string, dataJson string, url string) (ret string, err error)
	VerifySignature(token string, timestamp string, nonce string, signature string) (ret string, err error)
}

type MpObjServantWithContext interface {
	GetAccessToken(tarsCtx context.Context, tenantId int32, appid string) (ret string, err error)
	RefreshAccessToken(tarsCtx context.Context, tenantId int32, appid string) (ret string, err error)
	GetUserInfo(tarsCtx context.Context, tenantId int32, appid string, openid string) (ret string, err error)
	SendTemplateMsg(tarsCtx context.Context, tenantId int32, appid string, openid string, templateId string, dataJson string, url string) (ret string, err error)
	VerifySignature(tarsCtx context.Context, token string, timestamp string, nonce string, signature string) (ret string, err error)
}

// MpObj struct
type MpObj struct {
	servant model.Servant
}

// NewMpObj creates a new MpObj servant.
func NewMpObj() *MpObj {
	return new(MpObj)
}

// NewMpObjClient creates a new MpObj client proxy for the given servant.
func NewMpObjClient(servant string, comm *tars.Communicator, option ...tars.EndpointManagerOption) *MpObj {
	client := new(MpObj)
	comm.StringToProxy(servant, client, option...)
	return client
}

// SetServant sets servant for the service.
func (obj *MpObj) SetServant(servant model.Servant) {
	obj.servant = servant
}

// TarsSetTimeout sets the timeout for the servant which is in ms.
func (obj *MpObj) TarsSetTimeout(timeout int) {
	obj.servant.TarsSetTimeout(timeout)
}

// TarsSetProtocol sets the protocol for the servant.
func (obj *MpObj) TarsSetProtocol(p model.Protocol) {
	obj.servant.TarsSetProtocol(p)
}

// Endpoints returns all active endpoint.Endpoint
func (obj *MpObj) Endpoints() []*endpoint.Endpoint {
	return obj.servant.Endpoints()
}

// AddServant adds servant  for the service.
func (obj *MpObj) AddServant(imp MpObjServant, servant string) {
	tars.AddServant(obj, imp, servant)
}

// AddServantWithContext adds servant  for the service with context.
func (obj *MpObj) AddServantWithContext(imp MpObjServantWithContext, servant string) {
	tars.AddServantWithContext(obj, imp, servant)
}

// GetAccessToken is the proxy function for the method defined in the tars file, with the context
func (obj *MpObj) GetAccessToken(tenantId int32, appid string, opts ...map[string]string) (string, error) {
	return obj.GetAccessTokenWithContext(context.Background(), tenantId, appid, opts...)
}

// GetAccessTokenWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MpObj) GetAccessTokenWithContext(tarsCtx context.Context, tenantId int32, appid string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(appid, 2)
	if err != nil {
		return ret, err
	}

	trace, ok := current.GetTarsTrace(tarsCtx)
	if ok && trace.Call() {
		var traceParam string
		trace.NewSpan()
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCS, uint(buf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value["tenantId"] = tenantId
			value["appid"] = appid
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCS), tarstrace.AnnotationCS, tars.GetClientConfig().ModuleName, obj.servant.Name(), "getAccessToken", 0, traceParam, "")
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 0, "getAccessToken", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}
	readBuf := codec.NewReader(tools.Int8ToByte(tarsResp.SBuffer))
	err = readBuf.ReadString(&ret, 0, true)
	if err != nil {
		return ret, err
	}

	if ok && trace.Call() {
		var traceParam string
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCR, uint(readBuf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value[""] = ret
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCR), tarstrace.AnnotationCR, tars.GetClientConfig().ModuleName, obj.servant.Name(), "getAccessToken", tarsResp.IRet, traceParam, "")
	}

	if len(opts) == 1 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
	} else if len(opts) == 2 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
		for k := range statusMap {
			delete(statusMap, k)
		}
		for k, v := range tarsResp.Status {
			statusMap[k] = v
		}
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// GetAccessTokenOneWayWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MpObj) GetAccessTokenOneWayWithContext(tarsCtx context.Context, tenantId int32, appid string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(appid, 2)
	if err != nil {
		return ret, err
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 1, "getAccessToken", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// RefreshAccessToken is the proxy function for the method defined in the tars file, with the context
func (obj *MpObj) RefreshAccessToken(tenantId int32, appid string, opts ...map[string]string) (string, error) {
	return obj.RefreshAccessTokenWithContext(context.Background(), tenantId, appid, opts...)
}

// RefreshAccessTokenWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MpObj) RefreshAccessTokenWithContext(tarsCtx context.Context, tenantId int32, appid string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(appid, 2)
	if err != nil {
		return ret, err
	}

	trace, ok := current.GetTarsTrace(tarsCtx)
	if ok && trace.Call() {
		var traceParam string
		trace.NewSpan()
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCS, uint(buf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value["tenantId"] = tenantId
			value["appid"] = appid
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCS), tarstrace.AnnotationCS, tars.GetClientConfig().ModuleName, obj.servant.Name(), "refreshAccessToken", 0, traceParam, "")
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 0, "refreshAccessToken", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}
	readBuf := codec.NewReader(tools.Int8ToByte(tarsResp.SBuffer))
	err = readBuf.ReadString(&ret, 0, true)
	if err != nil {
		return ret, err
	}

	if ok && trace.Call() {
		var traceParam string
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCR, uint(readBuf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value[""] = ret
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCR), tarstrace.AnnotationCR, tars.GetClientConfig().ModuleName, obj.servant.Name(), "refreshAccessToken", tarsResp.IRet, traceParam, "")
	}

	if len(opts) == 1 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
	} else if len(opts) == 2 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
		for k := range statusMap {
			delete(statusMap, k)
		}
		for k, v := range tarsResp.Status {
			statusMap[k] = v
		}
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// RefreshAccessTokenOneWayWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MpObj) RefreshAccessTokenOneWayWithContext(tarsCtx context.Context, tenantId int32, appid string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(appid, 2)
	if err != nil {
		return ret, err
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 1, "refreshAccessToken", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// GetUserInfo is the proxy function for the method defined in the tars file, with the context
func (obj *MpObj) GetUserInfo(tenantId int32, appid string, openid string, opts ...map[string]string) (string, error) {
	return obj.GetUserInfoWithContext(context.Background(), tenantId, appid, openid, opts...)
}

// GetUserInfoWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MpObj) GetUserInfoWithContext(tarsCtx context.Context, tenantId int32, appid string, openid string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(appid, 2)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(openid, 3)
	if err != nil {
		return ret, err
	}

	trace, ok := current.GetTarsTrace(tarsCtx)
	if ok && trace.Call() {
		var traceParam string
		trace.NewSpan()
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCS, uint(buf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value["tenantId"] = tenantId
			value["appid"] = appid
			value["openid"] = openid
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCS), tarstrace.AnnotationCS, tars.GetClientConfig().ModuleName, obj.servant.Name(), "getUserInfo", 0, traceParam, "")
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 0, "getUserInfo", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}
	readBuf := codec.NewReader(tools.Int8ToByte(tarsResp.SBuffer))
	err = readBuf.ReadString(&ret, 0, true)
	if err != nil {
		return ret, err
	}

	if ok && trace.Call() {
		var traceParam string
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCR, uint(readBuf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value[""] = ret
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCR), tarstrace.AnnotationCR, tars.GetClientConfig().ModuleName, obj.servant.Name(), "getUserInfo", tarsResp.IRet, traceParam, "")
	}

	if len(opts) == 1 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
	} else if len(opts) == 2 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
		for k := range statusMap {
			delete(statusMap, k)
		}
		for k, v := range tarsResp.Status {
			statusMap[k] = v
		}
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// GetUserInfoOneWayWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MpObj) GetUserInfoOneWayWithContext(tarsCtx context.Context, tenantId int32, appid string, openid string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(appid, 2)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(openid, 3)
	if err != nil {
		return ret, err
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 1, "getUserInfo", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// SendTemplateMsg is the proxy function for the method defined in the tars file, with the context
func (obj *MpObj) SendTemplateMsg(tenantId int32, appid string, openid string, templateId string, dataJson string, url string, opts ...map[string]string) (string, error) {
	return obj.SendTemplateMsgWithContext(context.Background(), tenantId, appid, openid, templateId, dataJson, url, opts...)
}

// SendTemplateMsgWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MpObj) SendTemplateMsgWithContext(tarsCtx context.Context, tenantId int32, appid string, openid string, templateId string, dataJson string, url string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(appid, 2)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(openid, 3)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(templateId, 4)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(dataJson, 5)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(url, 6)
	if err != nil {
		return ret, err
	}

	trace, ok := current.GetTarsTrace(tarsCtx)
	if ok && trace.Call() {
		var traceParam string
		trace.NewSpan()
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCS, uint(buf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value["tenantId"] = tenantId
			value["appid"] = appid
			value["openid"] = openid
			value["templateId"] = templateId
			value["dataJson"] = dataJson
			value["url"] = url
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCS), tarstrace.AnnotationCS, tars.GetClientConfig().ModuleName, obj.servant.Name(), "sendTemplateMsg", 0, traceParam, "")
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 0, "sendTemplateMsg", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}
	readBuf := codec.NewReader(tools.Int8ToByte(tarsResp.SBuffer))
	err = readBuf.ReadString(&ret, 0, true)
	if err != nil {
		return ret, err
	}

	if ok && trace.Call() {
		var traceParam string
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCR, uint(readBuf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value[""] = ret
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCR), tarstrace.AnnotationCR, tars.GetClientConfig().ModuleName, obj.servant.Name(), "sendTemplateMsg", tarsResp.IRet, traceParam, "")
	}

	if len(opts) == 1 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
	} else if len(opts) == 2 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
		for k := range statusMap {
			delete(statusMap, k)
		}
		for k, v := range tarsResp.Status {
			statusMap[k] = v
		}
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// SendTemplateMsgOneWayWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MpObj) SendTemplateMsgOneWayWithContext(tarsCtx context.Context, tenantId int32, appid string, openid string, templateId string, dataJson string, url string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteInt32(tenantId, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(appid, 2)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(openid, 3)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(templateId, 4)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(dataJson, 5)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(url, 6)
	if err != nil {
		return ret, err
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 1, "sendTemplateMsg", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// VerifySignature is the proxy function for the method defined in the tars file, with the context
func (obj *MpObj) VerifySignature(token string, timestamp string, nonce string, signature string, opts ...map[string]string) (string, error) {
	return obj.VerifySignatureWithContext(context.Background(), token, timestamp, nonce, signature, opts...)
}

// VerifySignatureWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MpObj) VerifySignatureWithContext(tarsCtx context.Context, token string, timestamp string, nonce string, signature string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteString(token, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(timestamp, 2)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(nonce, 3)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(signature, 4)
	if err != nil {
		return ret, err
	}

	trace, ok := current.GetTarsTrace(tarsCtx)
	if ok && trace.Call() {
		var traceParam string
		trace.NewSpan()
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCS, uint(buf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value["token"] = token
			value["timestamp"] = timestamp
			value["nonce"] = nonce
			value["signature"] = signature
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCS), tarstrace.AnnotationCS, tars.GetClientConfig().ModuleName, obj.servant.Name(), "verifySignature", 0, traceParam, "")
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 0, "verifySignature", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}
	readBuf := codec.NewReader(tools.Int8ToByte(tarsResp.SBuffer))
	err = readBuf.ReadString(&ret, 0, true)
	if err != nil {
		return ret, err
	}

	if ok && trace.Call() {
		var traceParam string
		traceParamFlag := trace.NeedTraceParam(tarstrace.EstCR, uint(readBuf.Len()))
		if traceParamFlag == tarstrace.EnpNormal {
			value := map[string]interface{}{}
			value[""] = ret
			jm, _ := json.Marshal(value)
			traceParam = string(jm)
		} else if traceParamFlag == tarstrace.EnpOverMaxLen {
			traceParam = `{"trace_param_over_max_len":true}`
		}
		tars.Trace(trace.GetTraceKey(tarstrace.EstCR), tarstrace.AnnotationCR, tars.GetClientConfig().ModuleName, obj.servant.Name(), "verifySignature", tarsResp.IRet, traceParam, "")
	}

	if len(opts) == 1 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
	} else if len(opts) == 2 {
		for k := range contextMap {
			delete(contextMap, k)
		}
		for k, v := range tarsResp.Context {
			contextMap[k] = v
		}
		for k := range statusMap {
			delete(statusMap, k)
		}
		for k, v := range tarsResp.Status {
			statusMap[k] = v
		}
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// VerifySignatureOneWayWithContext is the proxy function for the method defined in the tars file, with the context
func (obj *MpObj) VerifySignatureOneWayWithContext(tarsCtx context.Context, token string, timestamp string, nonce string, signature string, opts ...map[string]string) (ret string, err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	buf := codec.NewBuffer()
	err = buf.WriteString(token, 1)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(timestamp, 2)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(nonce, 3)
	if err != nil {
		return ret, err
	}

	err = buf.WriteString(signature, 4)
	if err != nil {
		return ret, err
	}

	var statusMap map[string]string
	var contextMap map[string]string
	if len(opts) == 1 {
		contextMap = opts[0]
	} else if len(opts) == 2 {
		contextMap = opts[0]
		statusMap = opts[1]
	}

	tarsResp := new(requestf.ResponsePacket)
	err = obj.servant.TarsInvoke(tarsCtx, 1, "verifySignature", buf.ToBytes(), statusMap, contextMap, tarsResp)
	if err != nil {
		return ret, err
	}

	_ = length
	_ = have
	_ = ty
	return ret, nil
}

// Dispatch is used to call the server side implement for the method defined in the tars file. withContext shows using context or not.
func (obj *MpObj) Dispatch(tarsCtx context.Context, val interface{}, tarsReq *requestf.RequestPacket, tarsResp *requestf.ResponsePacket, withContext bool) (err error) {
	var (
		length int32
		have   bool
		ty     byte
	)
	readBuf := codec.NewReader(tools.Int8ToByte(tarsReq.SBuffer))
	buf := codec.NewBuffer()
	switch tarsReq.SFuncName {
	case "getAccessToken":
		var tenantId int32
		var appid string
		if tarsReq.IVersion == basef.TARSVERSION {
			err = readBuf.ReadInt32(&tenantId, 1, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&appid, 2, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			reqTup := tup.NewUniAttribute()
			reqTup.Decode(readBuf)

			var tupBuffer []byte

			reqTup.GetBuffer("tenantId", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadInt32(&tenantId, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("appid", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&appid, 0, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			var jsonData map[string]interface{}
			decoder := json.NewDecoder(bytes.NewReader(readBuf.ToBytes()))
			decoder.UseNumber()
			err = decoder.Decode(&jsonData)
			if err != nil {
				return fmt.Errorf("decode reqpacket failed, error: %+v", err)
			}
			{
				jsonStr, _ := json.Marshal(jsonData["tenantId"])
				if err = json.Unmarshal(jsonStr, &tenantId); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["appid"])
				if err = json.Unmarshal(jsonStr, &appid); err != nil {
					return err
				}
			}
		} else {
			err = fmt.Errorf("decode reqpacket fail, error version: %d", tarsReq.IVersion)
			return err
		}

		trace, ok := current.GetTarsTrace(tarsCtx)
		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSR, uint(readBuf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value["tenantId"] = tenantId
				value["appid"] = appid
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSR), tarstrace.AnnotationSR, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "getAccessToken", 0, traceParam, "")
		}

		var funRet string
		if !withContext {
			imp := val.(MpObjServant)
			funRet, err = imp.GetAccessToken(tenantId, appid)
		} else {
			imp := val.(MpObjServantWithContext)
			funRet, err = imp.GetAccessToken(tarsCtx, tenantId, appid)
		}
		if err != nil {
			return err
		}

		if tarsReq.IVersion == basef.TARSVERSION {
			buf.Reset()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			rspTup := tup.NewUniAttribute()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}

			rspTup.PutBuffer("", buf.ToBytes())
			rspTup.PutBuffer("tars_ret", buf.ToBytes())

			buf.Reset()
			err = rspTup.Encode(buf)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			rspJson := map[string]interface{}{}
			rspJson["tars_ret"] = funRet

			var rspByte []byte
			if rspByte, err = json.Marshal(rspJson); err != nil {
				return err
			}

			buf.Reset()
			err = buf.WriteSliceUint8(rspByte)
			if err != nil {
				return err
			}
		}

		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSS, uint(buf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value[""] = funRet
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSS), tarstrace.AnnotationSS, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "getAccessToken", 0, traceParam, "")
		}
	case "refreshAccessToken":
		var tenantId int32
		var appid string
		if tarsReq.IVersion == basef.TARSVERSION {
			err = readBuf.ReadInt32(&tenantId, 1, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&appid, 2, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			reqTup := tup.NewUniAttribute()
			reqTup.Decode(readBuf)

			var tupBuffer []byte

			reqTup.GetBuffer("tenantId", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadInt32(&tenantId, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("appid", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&appid, 0, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			var jsonData map[string]interface{}
			decoder := json.NewDecoder(bytes.NewReader(readBuf.ToBytes()))
			decoder.UseNumber()
			err = decoder.Decode(&jsonData)
			if err != nil {
				return fmt.Errorf("decode reqpacket failed, error: %+v", err)
			}
			{
				jsonStr, _ := json.Marshal(jsonData["tenantId"])
				if err = json.Unmarshal(jsonStr, &tenantId); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["appid"])
				if err = json.Unmarshal(jsonStr, &appid); err != nil {
					return err
				}
			}
		} else {
			err = fmt.Errorf("decode reqpacket fail, error version: %d", tarsReq.IVersion)
			return err
		}

		trace, ok := current.GetTarsTrace(tarsCtx)
		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSR, uint(readBuf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value["tenantId"] = tenantId
				value["appid"] = appid
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSR), tarstrace.AnnotationSR, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "refreshAccessToken", 0, traceParam, "")
		}

		var funRet string
		if !withContext {
			imp := val.(MpObjServant)
			funRet, err = imp.RefreshAccessToken(tenantId, appid)
		} else {
			imp := val.(MpObjServantWithContext)
			funRet, err = imp.RefreshAccessToken(tarsCtx, tenantId, appid)
		}
		if err != nil {
			return err
		}

		if tarsReq.IVersion == basef.TARSVERSION {
			buf.Reset()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			rspTup := tup.NewUniAttribute()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}

			rspTup.PutBuffer("", buf.ToBytes())
			rspTup.PutBuffer("tars_ret", buf.ToBytes())

			buf.Reset()
			err = rspTup.Encode(buf)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			rspJson := map[string]interface{}{}
			rspJson["tars_ret"] = funRet

			var rspByte []byte
			if rspByte, err = json.Marshal(rspJson); err != nil {
				return err
			}

			buf.Reset()
			err = buf.WriteSliceUint8(rspByte)
			if err != nil {
				return err
			}
		}

		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSS, uint(buf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value[""] = funRet
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSS), tarstrace.AnnotationSS, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "refreshAccessToken", 0, traceParam, "")
		}
	case "getUserInfo":
		var tenantId int32
		var appid string
		var openid string
		if tarsReq.IVersion == basef.TARSVERSION {
			err = readBuf.ReadInt32(&tenantId, 1, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&appid, 2, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&openid, 3, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			reqTup := tup.NewUniAttribute()
			reqTup.Decode(readBuf)

			var tupBuffer []byte

			reqTup.GetBuffer("tenantId", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadInt32(&tenantId, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("appid", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&appid, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("openid", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&openid, 0, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			var jsonData map[string]interface{}
			decoder := json.NewDecoder(bytes.NewReader(readBuf.ToBytes()))
			decoder.UseNumber()
			err = decoder.Decode(&jsonData)
			if err != nil {
				return fmt.Errorf("decode reqpacket failed, error: %+v", err)
			}
			{
				jsonStr, _ := json.Marshal(jsonData["tenantId"])
				if err = json.Unmarshal(jsonStr, &tenantId); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["appid"])
				if err = json.Unmarshal(jsonStr, &appid); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["openid"])
				if err = json.Unmarshal(jsonStr, &openid); err != nil {
					return err
				}
			}
		} else {
			err = fmt.Errorf("decode reqpacket fail, error version: %d", tarsReq.IVersion)
			return err
		}

		trace, ok := current.GetTarsTrace(tarsCtx)
		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSR, uint(readBuf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value["tenantId"] = tenantId
				value["appid"] = appid
				value["openid"] = openid
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSR), tarstrace.AnnotationSR, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "getUserInfo", 0, traceParam, "")
		}

		var funRet string
		if !withContext {
			imp := val.(MpObjServant)
			funRet, err = imp.GetUserInfo(tenantId, appid, openid)
		} else {
			imp := val.(MpObjServantWithContext)
			funRet, err = imp.GetUserInfo(tarsCtx, tenantId, appid, openid)
		}
		if err != nil {
			return err
		}

		if tarsReq.IVersion == basef.TARSVERSION {
			buf.Reset()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			rspTup := tup.NewUniAttribute()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}

			rspTup.PutBuffer("", buf.ToBytes())
			rspTup.PutBuffer("tars_ret", buf.ToBytes())

			buf.Reset()
			err = rspTup.Encode(buf)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			rspJson := map[string]interface{}{}
			rspJson["tars_ret"] = funRet

			var rspByte []byte
			if rspByte, err = json.Marshal(rspJson); err != nil {
				return err
			}

			buf.Reset()
			err = buf.WriteSliceUint8(rspByte)
			if err != nil {
				return err
			}
		}

		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSS, uint(buf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value[""] = funRet
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSS), tarstrace.AnnotationSS, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "getUserInfo", 0, traceParam, "")
		}
	case "sendTemplateMsg":
		var tenantId int32
		var appid string
		var openid string
		var templateId string
		var dataJson string
		var url string
		if tarsReq.IVersion == basef.TARSVERSION {
			err = readBuf.ReadInt32(&tenantId, 1, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&appid, 2, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&openid, 3, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&templateId, 4, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&dataJson, 5, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&url, 6, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			reqTup := tup.NewUniAttribute()
			reqTup.Decode(readBuf)

			var tupBuffer []byte

			reqTup.GetBuffer("tenantId", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadInt32(&tenantId, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("appid", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&appid, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("openid", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&openid, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("templateId", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&templateId, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("dataJson", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&dataJson, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("url", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&url, 0, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			var jsonData map[string]interface{}
			decoder := json.NewDecoder(bytes.NewReader(readBuf.ToBytes()))
			decoder.UseNumber()
			err = decoder.Decode(&jsonData)
			if err != nil {
				return fmt.Errorf("decode reqpacket failed, error: %+v", err)
			}
			{
				jsonStr, _ := json.Marshal(jsonData["tenantId"])
				if err = json.Unmarshal(jsonStr, &tenantId); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["appid"])
				if err = json.Unmarshal(jsonStr, &appid); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["openid"])
				if err = json.Unmarshal(jsonStr, &openid); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["templateId"])
				if err = json.Unmarshal(jsonStr, &templateId); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["dataJson"])
				if err = json.Unmarshal(jsonStr, &dataJson); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["url"])
				if err = json.Unmarshal(jsonStr, &url); err != nil {
					return err
				}
			}
		} else {
			err = fmt.Errorf("decode reqpacket fail, error version: %d", tarsReq.IVersion)
			return err
		}

		trace, ok := current.GetTarsTrace(tarsCtx)
		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSR, uint(readBuf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value["tenantId"] = tenantId
				value["appid"] = appid
				value["openid"] = openid
				value["templateId"] = templateId
				value["dataJson"] = dataJson
				value["url"] = url
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSR), tarstrace.AnnotationSR, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "sendTemplateMsg", 0, traceParam, "")
		}

		var funRet string
		if !withContext {
			imp := val.(MpObjServant)
			funRet, err = imp.SendTemplateMsg(tenantId, appid, openid, templateId, dataJson, url)
		} else {
			imp := val.(MpObjServantWithContext)
			funRet, err = imp.SendTemplateMsg(tarsCtx, tenantId, appid, openid, templateId, dataJson, url)
		}
		if err != nil {
			return err
		}

		if tarsReq.IVersion == basef.TARSVERSION {
			buf.Reset()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			rspTup := tup.NewUniAttribute()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}

			rspTup.PutBuffer("", buf.ToBytes())
			rspTup.PutBuffer("tars_ret", buf.ToBytes())

			buf.Reset()
			err = rspTup.Encode(buf)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			rspJson := map[string]interface{}{}
			rspJson["tars_ret"] = funRet

			var rspByte []byte
			if rspByte, err = json.Marshal(rspJson); err != nil {
				return err
			}

			buf.Reset()
			err = buf.WriteSliceUint8(rspByte)
			if err != nil {
				return err
			}
		}

		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSS, uint(buf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value[""] = funRet
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSS), tarstrace.AnnotationSS, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "sendTemplateMsg", 0, traceParam, "")
		}
	case "verifySignature":
		var token string
		var timestamp string
		var nonce string
		var signature string
		if tarsReq.IVersion == basef.TARSVERSION {
			err = readBuf.ReadString(&token, 1, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&timestamp, 2, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&nonce, 3, true)
			if err != nil {
				return err
			}
			err = readBuf.ReadString(&signature, 4, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			reqTup := tup.NewUniAttribute()
			reqTup.Decode(readBuf)

			var tupBuffer []byte

			reqTup.GetBuffer("token", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&token, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("timestamp", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&timestamp, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("nonce", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&nonce, 0, true)
			if err != nil {
				return err
			}

			reqTup.GetBuffer("signature", &tupBuffer)
			readBuf.Reset(tupBuffer)
			err = readBuf.ReadString(&signature, 0, true)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			var jsonData map[string]interface{}
			decoder := json.NewDecoder(bytes.NewReader(readBuf.ToBytes()))
			decoder.UseNumber()
			err = decoder.Decode(&jsonData)
			if err != nil {
				return fmt.Errorf("decode reqpacket failed, error: %+v", err)
			}
			{
				jsonStr, _ := json.Marshal(jsonData["token"])
				if err = json.Unmarshal(jsonStr, &token); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["timestamp"])
				if err = json.Unmarshal(jsonStr, &timestamp); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["nonce"])
				if err = json.Unmarshal(jsonStr, &nonce); err != nil {
					return err
				}
			}
			{
				jsonStr, _ := json.Marshal(jsonData["signature"])
				if err = json.Unmarshal(jsonStr, &signature); err != nil {
					return err
				}
			}
		} else {
			err = fmt.Errorf("decode reqpacket fail, error version: %d", tarsReq.IVersion)
			return err
		}

		trace, ok := current.GetTarsTrace(tarsCtx)
		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSR, uint(readBuf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value["token"] = token
				value["timestamp"] = timestamp
				value["nonce"] = nonce
				value["signature"] = signature
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSR), tarstrace.AnnotationSR, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "verifySignature", 0, traceParam, "")
		}

		var funRet string
		if !withContext {
			imp := val.(MpObjServant)
			funRet, err = imp.VerifySignature(token, timestamp, nonce, signature)
		} else {
			imp := val.(MpObjServantWithContext)
			funRet, err = imp.VerifySignature(tarsCtx, token, timestamp, nonce, signature)
		}
		if err != nil {
			return err
		}

		if tarsReq.IVersion == basef.TARSVERSION {
			buf.Reset()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.TUPVERSION {
			rspTup := tup.NewUniAttribute()

			err = buf.WriteString(funRet, 0)
			if err != nil {
				return err
			}

			rspTup.PutBuffer("", buf.ToBytes())
			rspTup.PutBuffer("tars_ret", buf.ToBytes())

			buf.Reset()
			err = rspTup.Encode(buf)
			if err != nil {
				return err
			}
		} else if tarsReq.IVersion == basef.JSONVERSION {
			rspJson := map[string]interface{}{}
			rspJson["tars_ret"] = funRet

			var rspByte []byte
			if rspByte, err = json.Marshal(rspJson); err != nil {
				return err
			}

			buf.Reset()
			err = buf.WriteSliceUint8(rspByte)
			if err != nil {
				return err
			}
		}

		if ok && trace.Call() {
			var traceParam string
			traceParamFlag := trace.NeedTraceParam(tarstrace.EstSS, uint(buf.Len()))
			if traceParamFlag == tarstrace.EnpNormal {
				value := map[string]interface{}{}
				value[""] = funRet
				jm, _ := json.Marshal(value)
				traceParam = string(jm)
			} else if traceParamFlag == tarstrace.EnpOverMaxLen {
				traceParam = `{"trace_param_over_max_len":true}`
			}
			tars.Trace(trace.GetTraceKey(tarstrace.EstSS), tarstrace.AnnotationSS, tars.GetClientConfig().ModuleName, tarsReq.SServantName, "verifySignature", 0, traceParam, "")
		}

	default:
		return fmt.Errorf("func mismatch")
	}
	var statusMap map[string]string
	if status, ok := current.GetResponseStatus(tarsCtx); ok && status != nil {
		statusMap = status
	}
	var contextMap map[string]string
	if ctx, ok := current.GetResponseContext(tarsCtx); ok && ctx != nil {
		contextMap = ctx
	}
	*tarsResp = requestf.ResponsePacket{
		IVersion:     tarsReq.IVersion,
		CPacketType:  0,
		IRequestId:   tarsReq.IRequestId,
		IMessageType: 0,
		IRet:         0,
		SBuffer:      tools.ByteToInt8(buf.ToBytes()),
		Status:       statusMap,
		SResultDesc:  "",
		Context:      contextMap,
	}

	_ = readBuf
	_ = buf
	_ = length
	_ = have
	_ = ty
	return nil
}
